esphome:
    name: radar-80mhz-water-sensor
    friendly_name: Radar 80Ghz Water Sensor
    # on_boot:
    #     then:
    #         - output.turn_on: mosfet_pin
    #         - delay: 0.5s
    # on_shutdown:
    #     then:
    #         - output.turn_off: mosfet_pin

esp32:
    board: esp32dev

external_components:
    - source: components

logger:
    level: DEBUG # Use DEBUG for normal operation, VERBOSE for troubleshooting

# output:
#     - platform: gpio
#       pin: GPIO2
#       id: mosfet_pin

uart:
    id: uart_bus
    # tx_pin: GPIO17 # Connect to sensor RX
    # rx_pin: GPIO16 # Connect to sensor TX
    tx_pin: GPIO1 # Connect to sensor RX
    rx_pin: GPIO3 # Connect to sensor TX
    baud_rate: 115200

sensor:
    - platform: hlk_ld8001h
      uart_id: uart_bus
      name: "Distance to Water"
      unit_of_measurement: "mm"
      update_interval: 3s
      #   installation_height: 2m # Distance from sensor to water empty level / tank bottom (0.15m - 40m)
      range: 2.5m # Default 10m, Max detection range (0.15m - 40m), 0.5-1m greater than installation_height
      water_depth_sensor: water_depth_id

    # Water level
    # This whole section is optional, and only used if you want to report the water depth
    # It literally just subtracts the distance to water from the installation height, but is included from the sensors docs, so i've included it here
    # - platform: template
    #   id: water_depth_id
    #   name: "Water Depth"
    #   unit_of_measurement: "mm"
    #   device_class: "distance"
    #   state_class: "measurement"
    #   accuracy_decimals: 1
