esphome:
    name: radar-water-sensor
    friendly_name: Radar Water Sensor
    on_boot:
        then:
            - output.turn_on: mosfet_pin
            - delay: 0.5s
    on_shutdown:
        then:
            - output.turn_off: mosfet_pin

esp32:
    board: esp32dev

external_components:
    - source: components

logger:
    level: DEBUG # Use DEBUG for normal operation, VERBOSE for troubleshooting

output:
    - platform: gpio
      pin: GPIO2
      id: mosfet_pin

# UART configuration is critical for this component
uart:
    id: uart_bus
    tx_pin: GPIO17 # Connect to sensor RX
    rx_pin: GPIO16 # Connect to sensor TX
    baud_rate: 115200

# Distance sensor for water level
sensor:
    - platform: hlk_ld2413
      uart_id: uart_bus
      name: "Water Level"
      unit_of_measurement: "mm"
      accuracy_decimals: 1
      update_interval: 2.4s # Default 2.4s, approx 15x the report cycle value
      # Optional configurations with defaults matching datasheet
      min_distance: 150mm # Default 150mm, Valid range: 150-10500mm
      max_distance: 2500mm # Default 10500mm, Valid range: 150-10500mm
      report_cycle: 160ms # Default 160ms, Valid range: 50-1000ms
      calibrate_on_boot: true # Default false, performs threshold calibration during setup
      filters:
          # Ignore the first 5
          - skip_initial: 10
      on_value:
          - lambda: |-
                // Received value
                float sensor_value = x;  // Store the filtered value
                ESP_LOGD("main", "Received filtered value of %.2f mm", sensor_value);
